# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM projectx13/xgo-1.11.x

MAINTAINER Péter Szilágyi <peterke@gmail.com>
