# Go cross compiler (xgo): Wildcard layer to the latest 1.9 release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM elgatito/xgo-1.9.5

MAINTAINER Péter Szilágyi <peterke@gmail.com>
