# Go cross compiler (xgo): Wildcard layer to the latest 1.11 release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM projectx13/xgo-1.11.4

MAINTAINER Péter Szilágyi <peterke@gmail.com>
